osx_image: xcode10.1
language: swift

cache: bundler
jobs:
  include:
    if: type = pull_request OR branch = master
    - stage: Unit Tests
      script:
        - bundle exec fastlane ios coverage
    - stage: deploy
      if: type = push AND branch = master
      script:
        - bundle exec fastlane ios deploy
