osx_image: xcode10.1
language: swift

cache: bundler
jobs:
  include:
    - stage: Unit Tests
      before_install:
        - bundle install
      script:
        - bundle exec fastlane ios coverage
    - stage: deploy
      script:
        - bundle show
