osx_image: xcode10.1
language: swift

cache: bundler

jobs:
  include:
    - stage: dependencies
      before_install:
        - bundle install
        - bundle update
      script: true
    - stage: test
      script:
        - bundle exec fastlane ios coverage
    - stage: deploy
      script:
        - bundle show
