osx_image: xcode10.1
language: swift

cache: bundler
jobs:
  include:
    - if: type = pull_request
    - stage: Unit Tests
      script:
        - bundle exec fastlane ios coverage
    - stage: deploy
      if: branch = master
      script:
        - bundle show
