update_fastlane

default_platform(:ios)

platform :ios do
  desc "Run all the tests"
  lane :tests do
    scan(
      project: "Grid.xcodeproj",
      scheme: "Grid",
      code_coverage: true
    )
  end

  desc "Runs coverage"
  lane :coverage do
    tests
    # xcov(
    #   project: "Grid.xcodeproj",
    #   scheme: "Grid",
    #   output_directory: "xcov_output"
    # )
  end
end
