default_platform(:ios)

platform :ios do
  desc "Run all the tests"
  lane :tests do
    scan(
      project: "Grid.xcodeproj",
      scheme: "Grid",
      code_coverage: true
    )
  end

  desc "Runs coverage"
  lane :coverage do
    tests
    xcov(
      project: "Grid.xcodeproj",
      scheme: "Grid",
      output_directory: "xcov_output"
    )
  end

  private_lane :update_version do |options|
    increment_version_number(bump_type: options[:bump])
    version_bump_podspec(path: "GridNet.podspec", bump_type: options[:bump])
  end

  desc "Create release PR from Develop to Master. Run this locally"
  lane :open_release do |options|
    update_version(bump: options[:bump])
    version_number = get_version_number(xcodeproj: 'Grid.xcodeproj', target: 'Grid')
    commit_version_bump(
      xcodeproj: "Grid.xcodeproj",
      message: "Bumping version to %s" % version_number,
      include: ["GridNet.podspec"]
    )
    push_to_git_remote
    create_pull_request(
      api_token: ENV["GITHUB_API_TOKEN"],
      repo: "rcarvalhosilva/Grid",
      title: "Release %s" % version_number,
      head: "develop",
      base: "master",
    )
  end

  desc "Deploy to CocoaPods"
  lane :deploy do
    pod_lib_lint
    version_number = get_version_number(xcodeproj: 'Grid.xcodeproj', target: 'Grid')
    tag_name = "#{version_number}"
    add_git_tag(
      tag: tag_name
    )
    push_to_git_remote
  end
end
